casbin/casbin-cpp

azure-pipelines.yml
casbin/casbin.vcxproj

I have added the config file for the azure pipeline but will require the casbin azure devops account credentials to setup the CI.

Added config file azure pipeline.

---

casbin/enforcer.cpp
casbin/enforcer.h
test/test.vcxproj
test/test.vcxproj.filters
test/test_enforcer.cpp

Add enforce functions with convinient interface, supporting vector<string> param.
Using original enforce functions:
``` C
Scope InitializeParams(string sub, string obj, string act) {
Scope scope = InitializeScope();
PushObject(scope, "r");
PushStringPropToObject(scope, "r", sub, "sub");
PushStringPropToObject(scope, "r", obj, "obj");
PushStringPropToObject(scope, "r", act, "act");
return scope;
}
void TestEnforce(Enforcer* e, Scope scope, bool res) {
Assert::AreEqual(res, e->Enforce(scope));
}
TEST_METHOD(TestBasicModel) {
string model = filePath("../examples/basic_model.conf");
string policy = filePath("../examples/basic_policy.csv");
Enforcer* e = Enforcer :: NewEnforcer(model, policy);
Scope scope;
scope = InitializeParams("alice", "data1", "read");
TestEnforce(e, scope, true);
scope = …
```

feat: add enforce functions with convenient interface.

---

README.md
casbin/enforcer.cpp
casbin/enforcer.h
casbin/enforcer_interface.h
casbin/internal_api.cpp
casbin/model/assertion.cpp
casbin/model/model.cpp
casbin/rbac/default_role_manager.cpp
casbin/rbac/default_role_manager.h
casbin/rbac_api.cpp
casbin/util/array_equals.cpp
test/test.vcxproj
test/test.vcxproj.filters
test/test_config.cpp
test/test_enforcer.cpp
test/test_management_api.cpp
test/test_model.cpp
test/test_model_enforcer.cpp
test/test_rbac_api.cpp
test/test_rbac_api_with_domains.cpp
test/test_util.cpp

Fix: https://github.com/casbin/casbin-cpp/issues/56

feat: Add Management, RBAC API, RBAC API with Domains tests and fix filePath function removal.

---

CMakeLists.txt

Signed-off-by: Zixuan Liu <nodeces@gmail.com>
The default using make, but I also consider cmake user, so I add CMakeLists.txt for support it.  CLion is most welcome.

chore: add CMakeLists.txt for support CLion

---

.gitignore
README.md
makefile

Signed-off-by: Zixuan Liu <nodeces@gmail.com>
/cc @divy9881

chore: add cmake support

---

casbin/ip_parser/exception/parserException.cpp
casbin/ip_parser/parser/parseCIDR.h

fix: change "ParseException.h" to "parseException.h"

---

casbin/enforcer.cpp

fix: assign value to uninitialized vector

---

casbin/enforcer.cpp
casbin/enforcer.h
casbin/management_api.cpp
casbin/model/function.cpp
casbin/model/function.h

Fix: https://github.com/casbin/casbin-cpp/issues/71
Fix: https://github.com/casbin/casbin-cpp/issues/74
Signed-off-by: chris <bigcat26@gmail.com>

fix: crash while initialize Enforcer without adapter bug

---

casbin/enforcer.cpp
casbin/model/function.cpp
casbin/model/scope_config.cpp
casbin/model/scope_config.h

duktape scope was not released
Signed-off-by: chris <bigcat26@gmail.com>

fix: memory leak

---

.gitignore
casbin/casbin.vcxproj
casbin/casbin.vcxproj.filters
casbin/enforcer_synced.h

This PR fixes #83 
Added in a header file for synced enforcer incorporating the features in [enforcer_synced.go](https://github.com/casbin/casbin/blob/master/enforcer_synced.go)
Reference: https://github.com/casbin/casbin-cpp/pull/83#issuecomment-810162142

feat: Added synced enforcer

---

.github/workflows/ci.yml
.travis.yml
README.md

feat: Replaced travis with GitHub Actions

---

test/test.vcxproj
test/test.vcxproj.filters
test/test_enforcer_synced.cpp

This PR fixes #38 
Reference: #93 
Added tests for `enforcer_synced.cpp` corresponding to `enforcer_synced_test.go`

feat: Added Tests for SyncedEnforcer

---

bindings/python/CMakeLists.txt
bindings/python/main.cpp
bindings/python/py_abac_data.cpp
bindings/python/py_casbin.h

This is intended to be merged after #129 is merged into `casbin:master`

feat: Added bindings for `casbin::ABACData`

---

casbin/enforcer.cpp
casbin/util/eval.cpp
casbin/util/util.h
include/casbin/casbin_helpers.h
tests/config_path.h
tests/model_enforcer_test.cpp

Fix: https://github.com/casbin/casbin-cpp/issues/102
+ feat: add abac_with_rule and test

feat: add abac_with_rule and test

---

casbin/enforcer.h
casbin/enforcer_interface.h
casbin/management_api.cpp
include/casbin/casbin_enforcer.h
tests/model_enforcer_test.cpp

+ add AddNamedMatchingFunc interface for enfocer.

feat: add AddNamedMatchingFunc interface for enfocer.

---

CMakeLists.txt
casbin/enforcer.cpp
casbin/exprtk/exprtk.hpp
casbin/model/evaluator.cpp
casbin/model/evaluator.h
examples/basic_with_root_model.conf
include/casbin/casbin_helpers.h
include/casbin/exprtk/exprtk.hpp
tests/model_enforcer_test.cpp

feat: add ExprtkEvaluator test for basic model and root model. 
fix: fix basic_with_root_model.conf and add "p" variable when Enforce with no policy.
fix: add bigobj option for windows.
fix: fix short string optimization bug in MSVC.
Signed-off-by: stonexx <1479765922@qq.com>

feat: add ExprtkEvaluator test for basic model and root model.

---

include/casbin/exprtk/exprtk.hpp

chore: Update ExprTk to the lastest version.

chore: Update Exprtk

---

casbin/enforcer.cpp
casbin/model/evaluator.cpp
include/casbin/model/evaluator.h
include/casbin/model/exprtk_config.h
tests/model_enforcer_test.cpp

+ Exprtk evaluator support RBAC with domain.
+ Use ExprtkFunctionFactory to generate different type exprtk function.

feat: exprtk evaluator support RBAC with domain

---

.github/workflows/ci.yml
.github/workflows/memcheck.yml
tests/CMakeLists.txt

+ Add memcheck for casbin by valgrind, current code may have memory problem.

chore: add ci for memcheck.

---

cmake/modules/Findjson.cmake

+ simplify json cmake download package

chore: simplify json cmake download package

---

casbin/enforcer_synced.cpp
include/casbin/enforcer_synced.h

+ ref [casbin-golang](https://github.com/casbin/casbin/blob/master/enforcer_synced.go#L30).

perf: use rwmutex to enhance enforcer_synced.

---

casbin/model/evaluator.cpp
casbin/util/built_in_functions.cpp
include/casbin/model/exprtk_config.h
include/casbin/util/built_in_functions.h
tests/built_in_functions_test.cpp

part of: #209 
add KeyGet(), KeyGet2() and KeyGet3() for built_in_functions

fix: add KeyGet for built_in_functions

---

examples/performance/rbac_with_pattern_large_scale_model.conf
examples/performance/rbac_with_pattern_large_scale_policy.csv
tests/benchmarks/config_path.h
tests/benchmarks/enforcer_cached_b.cpp
tests/benchmarks/model_b.cpp
tests/benchmarks/model_b_inten.cpp

Part of: https://github.com/casbin/casbin/issues/1049
Command:
```bash
mkdir build & cd build
cmake .. -DCMAKE_BUILD_TYPE:STRING=Release -DINTENSIVE_BENCHMARK:BOOL=ON
cmake --build . --config Release
```
Notes:
1. Without the support for `KeyMatch4` and `ABAC` model in `Casbin-cpp` , some test cases are missing. 
2. As for `BenchmarkCachedRBACModelMediumParallel`, there are no routines in C++ so it is not enabled.
Implementation in Golang version:
3. I have tested on Windows, WSL, and Ubuntu. However, I encounter some errors triggered by the existing codes(only works well on Windows). I'm not sure whether it should be cared about or not.
WSL:
Ubuntu, compiled locally:
Ubuntu, compiled on WSL:
Caused by:
```cpp
static const std::vector<std::vector<std::string>> s_policy = {{"alice", …
```

test: update the benchmark tests

---

casbin/enforcer.cpp
include/casbin/enforcer.h
include/casbin/enforcer_interface.h
tests/enforcer_test.cpp

Fix: https://github.com/casbin/casbin-cpp/issues/218
feat: support EnforceEx & EnforceExWithMatcher

feat: support EnforceEx & EnforceExWithMatcher

---

casbin/enforcer.cpp
casbin/model/evaluator.cpp
include/casbin/model/evaluator.h
include/casbin/model/exprtk_config.h
tests/built_in_functions_test.cpp

Fixes https://github.com/casbin/casbin-cpp/issues/215

fix: register keyGet* function for evaluator

---

casbin/enforcer_synced.cpp
include/casbin/enforcer.h
include/casbin/enforcer_synced.h
tests/enforcer_synced_test.cpp

* SyncedEnforcer::Enforce ReadLock-->WriteLock
* SyncedEnforcer::BatchEnforce ReadLock-->WriteLock, fix deadlock

fix: Multithread usage of SyncedEnforcer::Enforce

---

include/casbin/exprtk/exprtk.hpp

Update ExprTk library to release tag 0.0.2

fix: update ExprTk dependency to v0.0.2

---

CMakeLists.txt

I test it on my project, it works.

feat: update CMakeLists.txt to fix issue

---

include/casbin/exprtk/exprtk.hpp
include/casbin/model/exprtk_config.h

Release notes: https://www.partow.net/programming/exprtk/exprtk_release_notes_v0.0.3.txt

feat: upgrade exprtk dependency to v0.0.3
