casbin/casbin-cpp

- casbin/enforcer.cpp
- casbin/enforcer.h
- casbin/enforcer_interface.h
- casbin/internal_api.cpp
- test/test_enforcer.cpp
- test/test_management_api.cpp
- test/test_model_enforcer.cpp
- test/test_rbac_api.cpp
- test/test_rbac_api_with_domains.cpp
Fix: https://github.com/casbin/casbin-cpp/issues/55
Using smart pointers instead of raw pointer,to avoid the leak of memory.
``` Cpp
class Enforcer : public IEnforcer{
private:
string model_path;
shared_ptr<Model> model;
FunctionMap func_map;
shared_ptr<Effector> eft;
shared_ptr<Adapter> adapter;
shared_ptr<Watcher> watcher;
...
```
> fix: Using smart pointers instead of raw pointer.

- casbin/casbin.vcxproj
- casbin/casbin.vcxproj.filters
- casbin/util/ticker.cpp
- casbin/util/ticker.h
This PR fixes #38
Reference: #89 
Most of the functions of SyncedEnforcer are straight-forward to implement but the `AutoLoadPolicy` needed a workaround since it utilized GoLang's ticker from the "time" module and concurrency used [here](https://github.com/casbin/casbin/blob/86d48b589606a67f8dc3c51486e8daa1b743f579/enforcer_synced.go#L60).
```go
ticker := time.NewTicker(d)
``` 
For this, I created a custom concurrent ticker that takes in the `chrono::duration` and a `function<void()>` for callback.
`Ticker::start()` will start a loop asynchronously (on a new thread). The parametric function will be called asynchronously as well. 
**Overheads involved:**
Apart from the futures obtained from ticker threads, …
> feat: Added async ticker

- casbin/casbin.vcxproj
- casbin/casbin.vcxproj.filters
- casbin/enforcer_synced.cpp
This PR fixes #38
Reference: #90 
Most of the functions of SyncedEnforcer were straight-forward to implement but the AutoLoadPolicy needed a workaround since it utilized GoLang's ticker from the "time" module and concurrency. For this, I created a custom concurrent ticker that takes in the duration and a function<void()> for a callback. Then passed in the following to callback of ticker which is called at every tick:
```cpp
[this]() {
Enforcer::LoadPolicy();
++n;
};
```
Note that `n` is an `atomic_int` which is thread-safe.
When StopAutoLoad() is called, the ticker stops all worker threads deployed by the ticker. However, this won't destroy the instance of the ticker. I also created test files to verify …
> feat: Added translation unit for synced enforcer

- test/test_enforcer_synced.cpp
This PR fixes #97 
I recently added tests for synced enforcer in #94 and it did not use the namespace introduced in #95.
> fix: Build on MS Visual Studio

- CMakeLists.txt
- casbin/CMakeLists.txt
Fixes #99 partially
Extended CMake config so as to add testing and CMake modules seamlessly. This won't change the build output/format we currently have, this is just an initial setup upon which we can add all the builds we want.
> feat: Initiate CMake configuration

- CMakeLists.txt
- casbin/CMakeLists.txt
- casbin/casbin.vcxproj
- casbin/casbin.vcxproj.filters
- casbin/enforcer.cpp
- casbin/enforcer.h
- casbin/enforcer_interface.h
- casbin/enforcer_synced.cpp
- casbin/internal_api.cpp
- casbin/log/Logger.h
- casbin/log/default_logger.h
- casbin/log/log_util.h
- casbin/logger.cpp
- casbin/management_api.cpp
- casbin/rbac_api.cpp
- casbin/rbac_api_with_domains.cpp
- makefile
Fixes #96 **partially**
---
- This code implements some methods of the enforcer API components from [casbin](https://github.com/casbin/casbin) to be on par with GoLang variant. Some of them includes :
```cpp
// Public API
std::vector<bool> BatchEnforce(const std::vector<std::vector<std::string>>& requests);
std::vector<bool> BatchEnforceWithMatcher(const std::string& matcher, const std::vector<std::vector<std::string>>& requests);
// Management API functions
bool UpdateGroupingPolicy(const std::vector<std::string>& oldRule, const std::vector<std::string>& newRule);
bool UpdateNamedGroupingPolicy(const std::string& ptype, const std::vector<std::string>& oldRule, const std::vector<std::string>& newRule);
bool …
```
> feat: Completion of Enforcer API

- .github/workflows/ci.yml
- .gitignore
- CMakeLists.txt
- README.md
- casbin/CMakeLists.txt
- casbin/casbin.vcxproj
- casbin/casbin.vcxproj.filters
- casbin/internal_api.cpp
- casbin/ip_parser/parser/Print.h
- casbin/ip_parser/parser/pch.h
- casbin/log/logger.cpp
- casbin/logger.cpp
- casbin/model/model.cpp
- casbin/model/model.h
- casbin/pch.h
- casbin/persist/watcher_update.h
- casbin/util/is_instance_of.cpp
- casbin/util/ticker.h
- test/test_management_api.cpp
Signed-off-by: Yash Pandey (YP) yash.btech.cs19@iiitranchi.ac.in
---
- Added implementation of `casbin::Enforcer::updatePolicy(...)` and `casbin::Enforcer::updatePolicies(...)` as per casbin (GoLang) implementation.
- Added tests for `casbin::Enforcer::UpdatePolicy()`, `casbin::Enforcer::UpdatePolicies()`, `casbin::Enforcer::UpdateGroupingPolicy()`, and `casbin::Enforcer::UpdateGroupingPolicies()` corresponding to tests in casbin (GoLang).
- Modified GitHub Actions CI to:
- Run CMake commands instead of makefile for UNIX
- Test build through CMake for Windows
---
**Important note** - One of the assert tests at the end of `tests/test_management_api.cpp` was failing for some reason.
> feat: Added implementation and tests for UpdatePolicy API

- casbin/casbin.h
- tests/CMakeLists.txt
- tests/built_in_functions_test.cpp
- tests/config_test.cpp
- tests/enforcer_synced_test.cpp
- tests/management_api_test.cpp
- tests/util_test.cpp
Signed-off-by: Yash Pandey(YP) <yash.btech.cs19@iiitranchi.ac.in>
---
This code adds tests for:
- Management API
- Utility functions/methods
- casbin's Config API
- Build-in functions
---
**Points to note**
- Tests for `casbin::SyncedEnforcer` are commented out. This is because GTest isn't made for testing multithreaded workloads. I tried multiple workarounds, but it doesn't seem to work out.
> test: Management API, Utility methods and more

- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- CMakeLists.txt
- README.md
- casbin/CMakeLists.txt
- cmake/modules/FindExtPackages.cmake
- cmake/modules/Findbenchmark.cmake
- tests/CMakeLists.txt
- tests/benchmarks/CMakeLists.txt
- tests/benchmarks/enforcer_cached_b.cpp
- tests/benchmarks/main.cpp
- tests/built_in_functions_test.cpp
- tests/config_test.cpp
- tests/enforcer_cached_test.cpp
- tests/enforcer_synced_test.cpp
- tests/enforcer_test.cpp
- tests/management_api_test.cpp
- tests/model_enforcer_test.cpp
- tests/model_test.cpp
- tests/rbac_api_test.cpp
- tests/rbac_api_with_domains_test.cpp
- tests/role_manager_test.cpp
- tests/util_test.cpp
---
This code will find [google/benchmark v1.5.5](https://github.com/google/benchmark) within the system. If not found, it will fetch it from GitHub and store it in `build/_deps` directory. Here's the workflow to get it running:
1. Checkout to `EmperorYP7/casbin-cpp:benchmark`.
2. Build the project using the commands stated in docs to be added in #113.
3. Go to `/build/tests/benchmarks` and run the executable named `casbin_benchmark`
> feat: Initiated benchmark workflow

- tests/benchmarks/CMakeLists.txt
- tests/benchmarks/config_path.h
- tests/benchmarks/enforcer_cached_b.cpp
---
This code:
- Adds benchmarks for analyzing the performance of the project at various scales of usage. This includes:
- `BenchmarkCachedRBACModelSmall`
- `BenchmarkCachedRBACModelMedium`
- `BenchmarkCachedRBACModelLarge` - not executed due to `AddPolicies()` resulting in segmentation fault
- `BenchmarkCachedRBACModelWithResourceRoles `
- `BenchmarkCachedRBACModelWithDomains`
- `BenchmarkCachedKeyMatchModel`
- `BenchmarkCachedRBACModelWithDeny`
- `BenchmarkCachedPriorityModel` - 
- `BenchmarkCachedRBACModelMediumParallel` - undefined hiatus while running this benchmark
> test: Benchmarks for `CachedEnforcer`

- tests/benchmarks/CMakeLists.txt
- tests/benchmarks/config_path.h
- tests/benchmarks/enforcer_cached_b.cpp
- tests/benchmarks/management_api_b.cpp
This code adds benchmarks for ManagementAPI. This includes:
- `Enforcer::HasPolicy()`
- `Enforcer::AddPolicy()`
- `Enforcer::RemovePolicy()`
for small, medium, and large workflows.
**Note:** This should be merged only after #116 is merged into master.
The large workflow benchmarks show that the management API functions are dramatically slower than that of GoLang.
> test: Benchmarks for ManagementAPI

- casbin/abac_data.cpp
- casbin/abac_data.h
- casbin/attribute_types.h
- casbin/data_types.h
- casbin/enforcer.cpp
- casbin/enforcer.h
- casbin/enforcer_cached.cpp
- casbin/enforcer_cached.h
- casbin/enforcer_interface.h
- casbin/enforcer_synced.cpp
- casbin/enforcer_synced.h
- casbin/model/model.cpp
- casbin/pch.h
- tests/benchmarks/enforcer_cached_b.cpp
- tests/enforcer_test.cpp
- tests/rbac_api_test.cpp
This code adds type definitions for accomodating `casbin::ABACData` within the entirety of the project.
The definitions are as follows:
- `AttributeValue`: The type of a value of an attribute
- `Attribute`: The type of an attribute containing the name and the value as a `std::pair`.
- `AttributeVector`: Vector of attributes.
- `AttributeList`: Initializer list of attributes.
- `AttributeMap`: Unordered map containing name and value of the attributes.
- `Data`: Type of Data for accomodating `ABACData`
- `DataVector`: Vector of `casbin::Data`
- `DataList`: Initializer list of `casbin::Data`
- `DataMap`: unordered map containing name and `casbin::Data`
> feat: Streamlined types

- tests/benchmarks/CMakeLists.txt
- tests/benchmarks/enforcer_cached_b.cpp
- tests/benchmarks/management_api_b.cpp
- tests/benchmarks/model_b.cpp
- tests/benchmarks/role_manager_b.cpp
Added Benchmarks for `casbin::Model` and `casbin::RoleManager`.
> test: Benchmarks for `Model` and `RoleManager`

- casbin/model/assertion.cpp
- casbin/model/assertion.h
- casbin/model/function.cpp
- casbin/model/function.h
- casbin/model/model.cpp
With reference to casbin/casbin-website#255, I tried to clean up the implementation of the model by reducing the numbers of constructor calls for `std::vector`, structured bindings and more.
This might not affect the actual performance of the enforcer directly, but is a valid and necessary cleanup.
> chore: Model Cleanup

- casbin/enforcer_interface.h
Hi,
I was getting compile errors on CentOS 8 and gcc 10.3.0 with bazel.
https://paste.ubuntu.com/p/W5Jj48sKpD/
Adding this line of #include fixes the issue.
> fix: compile error on some environments

- bindings/python/CMakeLists.txt
- bindings/python/main.cpp
- bindings/python/py_enforcer.cpp
- casbin/CMakeLists.txt
- tests/CMakeLists.txt
- tests/benchmarks/CMakeLists.txt
---
This code:
- Adds `casbin::Enforcer` definitions in python bindings.
- The bindings are compiled into `pycasbin.so` file in UNIX and `pycasbin.pyd` in Windows.
- This file can now be added into the PATH variable and can be imported directly in Python.
- Configures the build system to compile targets with `-fPIC` flag
> feat: Added python bindings for `casbin::Enforcer`

- CMakeLists.txt
- bindings/python/CMakeLists.txt
- bindings/python/main.cpp
- bindings/python/py_cached_enforcer.cpp
- bindings/python/py_casbin.h
- bindings/python/py_enforcer.cpp
- casbin/enforcer_cached.h
---
This code:
- Adds bindings for `casbin::CachedEnforcer`
- The methods added are only the constructors and overrides
- The rest of the methods are inherited from `casbin::Enforcer` just like the C++ implementation.
- Adds versioning to `pycasbin` module through CMake configuration.
- Refactors the workflow by passing the reference of the `py::module` object to functions.
- Each function then defines a binding for all the methods present in the corresponding C++ translation unit.
When I try to build the `pycasbin` target, it throws an error wherever there is an occurrence of `casbin::Scope` in the binding definition. Considering the fact that pycasbin is a client-centric interface, exposing `casbin::Scope` is redundant, …
> feat: Added bindings for `CachedEnforcer`

- tests/CMakeLists.txt
- tests/benchmarks/CMakeLists.txt
- tests/benchmarks/enforcer_cached_b.cpp
- tests/config_path.h
- tests/enforcer_cached_test.cpp
- tests/enforcer_synced_test.cpp
- tests/enforcer_test.cpp
- tests/management_api_test.cpp
- tests/model_enforcer_test.cpp
- tests/model_test.cpp
- tests/rbac_api_test.cpp
- tests/rbac_api_with_domains_test.cpp
---
This code:
- Removes the relative paths used in `config_path`.
- Modifies `config_path` so as to abstract the absolute path to the `CMAKE_SOURCE_DIR` and use it to get the path to test entities.
> feat: Added `config_path` for test entities

- .gitignore
- bindings/python/CMakeLists.txt
- bindings/python/main.cpp
- bindings/python/py_casbin.h
- bindings/python/py_model.cpp
- tests/python/test_model.py
---
This code:
- Adds python bindings for `casbin::Model`.
- Adds the support for calling static member functions of `casbin::Model` in python.
- Adds unit tests in python for the bindings.
- Configures the build system and pybind workflow to include `py_model.cpp`
> feat: Added bindings for `casbin::Model`

- CMakeLists.txt
- bindings/python/CMakeLists.txt
- bindings/python/main.cpp
- bindings/python/py_casbin.h
- bindings/python/py_config.cpp
- bindings/python/py_model.cpp
- casbin/CMakeLists.txt
- casbin/config/config.cpp
- casbin/config/config.h
- casbin/model/model.cpp
- casbin/model/model.h
- include/casbin/casbin_helpers.h
- tests/model_test.cpp
- tests/python/config_path.py
- tests/python/pycasbin_test_suite.py
- tests/python/test_config.py
- tests/python/test_model.py
---
This code:
- Implements python bindings for `casbin::Config`
- Modified the API to facilitate the bindings
- Added python tests for `pycasbin.Config` and `pycasbin.Model`
The workflow enabled by the API exposed to the python side can be abstracted as follows:
```python
import pycasbin as casbin
config = casbin.Config.NewConfig('path/to/config/file.ini')
config = casbin.Config.NewConfigFromText('<contents of the config>')
ok = config.GetBool('<key>')
num_value = config.GetInt('<key')
model = casbin.Model.NewModel() # empty model
model = casbin.Model.NewModelFromFile('path/to/model.conf')
model = casbin.Model.NewModelFromString('<contents of the model>')
config = casbin.Config.NewConfig('path/to/model.conf')
model = …
```
> feat: Added python bindings for `casbin::Config`

- bindings/python/CMakeLists.txt
- bindings/python/main.cpp
- bindings/python/py_cached_enforcer.cpp
- bindings/python/py_casbin.h
- bindings/python/py_enforcer.cpp
- bindings/python/py_synced_enforcer.cpp
- casbin/enforcer_cached.cpp
- casbin/enforcer_cached.h
- casbin/enforcer_synced.cpp
- casbin/enforcer_synced.h
- include/casbin/casbin_enforcer.h
- tests/python/pycasbin_test_suite.py
- tests/python/test_cached_enforcer.py
- tests/python/test_synced_enforcer.py
---
This code:
- Adds bindings for `SyncedEnforcer`
- Adds Unit tests for python bindings of `SyncedEnforcer` and `CachedEnforcer`
- Makes adjustments in the API which are necessary for the bindings to work properly
The synced enforcer tests seem to freeze the console which is not expected. This shall be addressed in the future.
> feat: Added bindings for `casbin::SyncedEnforcer`

- .github/workflows/ci.yml
- CMakeLists.txt
- bindings/python/CMakeLists.txt
- casbin/CMakeLists.txt
- cmake/modules/FindExtPackages.cmake
- cmake/modules/Findbenchmark.cmake
- cmake/modules/Findgoogletest.cmake
- cmake/modules/Findpybind11.cmake
This code:
- Changes the `CMAKE_PROJECT_NAME` to casbin and `CMAKE_PROJECT_VERSION` to 1.37.1
- Removes unnecessary installations
- Properly installs `pycasbin.so`/`pycasbin.pyd` to its desired path
- Configures include paths to be inline with the [intended client-side configuration](https://github.com/EmperorYP7/casbin-CMake-setup)
> chore: Updated project config

- casbin/enforcer.cpp
- casbin/util/split.cpp
Fix: https://github.com/casbin/casbin-cpp/issues/143
* Having the list of functions growing with every enforcement makes the context creation slower and slower, every enforcement is linearly slower than the previous.
* Having a 100k string vector reserved makes enforcement very slow and it is invaluable.
> perf: Performance Enhancement

- casbin/exception/casbin_adapter_exception.h
- casbin/exception/casbin_enforcer_exception.h
- casbin/exception/casbin_rbac_exception.h
- casbin/exception/illegal_argument_exception.h
- casbin/exception/io_exception.h
- casbin/exception/missing_required_sections.h
- casbin/exception/unsupported_operation_exception.h
Signed-off-by: William Michaels <bill@polarity.io>
- Provide access to std::exception::what() when catching Casbin exceptions
> feat: inheritance of exceptions public

- casbin/enforcer_cached.h
- include/casbin/casbin_types.h
Signed-off-by: William Michaels <bill@polarity.io>
- add `<string>` to casbin_types.h for visibility of `std::hash<std::string>` of CachedEnforcer's `std::unordered_map`
- add default virtual destructor
```
/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.2.0
```
> fix: Use of CachedEnforcer throws error from clang

- bindings/python/CMakeLists.txt
- bindings/python/main.cpp
- bindings/python/py_adapter.cpp
- bindings/python/py_casbin.h
- casbin/persist/file_adapter/batch_file_adapter.cpp
- casbin/persist/file_adapter/batch_file_adapter.h
- casbin/persist/file_adapter/file_adapter.cpp
- casbin/persist/file_adapter/file_adapter.h
- casbin/util/array_to_string.cpp
- include/casbin/casbin_helpers.h
- tests/python/pycasbin_test_suite.py
- tests/python/test_adapter.py
- tests/python/test_enforcer.py
+ I acciently delete this branch and close the [pr](https://github.com/casbin/casbin-cpp/pull/163).
+ [First commit](https://github.com/casbin/casbin-cpp/commit/5557955da80b86ac9c2212070e7a46192e1d3d6b) 
+ Fix `FileAdapter.SavePolicy()`
+ Add a new FileAdapter interface to use in python like [casbin::Config](https://github.com/casbin/casbin-cpp/blob/abaa2174f0a4c6df2a25c21c388c15939f472655/casbin/config/config.h#L55).
+ Fix `ArrayToString(const std::vector<std::string>& arr)`
+ `arr` usually be a line of policy keys without `p` or `g`, (e.g. `arr = {"alice", "data1", "read"}`).
+ Before `ArrayToString(const std::vector<std::string>& arr)`, `arr` will return `alice,  alice, data1, read`. `alice` will generate twice.
+ [Second commit](https://github.com/casbin/casbin-cpp/pull/164/commits/a0a …
> feat: add pycasbin adopter and test.

- bindings/python/CMakeLists.txt
- casbin/CMakeLists.txt
- casbin/data_types.h
- casbin/enforcer.cpp
- casbin/model/scope_config.cpp
- casbin/model/scope_config.h
- cmake/modules/FindExtPackages.cmake
- cmake/modules/Findjson.cmake
- include/casbin/casbin_helpers.h
- include/casbin/casbin_types.h
- tests/CMakeLists.txt
- tests/benchmarks/CMakeLists.txt
- tests/config_path.h
- tests/enforcer_test.cpp
- tests/model_enforcer_test.cpp
+ Link to this [issue](https://github.com/casbin/casbin-cpp/issues/165).
+ Add a json parser to build duktape object.
+ Test `double`, `int`, `bool`, `string` and `object`.
> feat: add json parser to build attribute in duktape

- cmake/modules/FindExtPackages.cmake
- cmake/modules/Findjson.cmake
+ update json version to 3.10.1.
+ If we include `json` in namesapce `casbin` we need add special version `json.hpp`, I don't know should I do that? @EmperorYP7
> fix: update json version to 3.10.1

- casbin/CMakeLists.txt
- casbin/util/eval.cpp
- casbin/util/util.h
- include/casbin/casbin_helpers.h
- tests/util_test.cpp
+ In adac model, we need test `eavl()` whether in the model matcher expression. Add a regex to test whether has `eval`.
+ `ReplaceEvalWithMap` replace the `eval(tokens)` by tokens value.
+ Add an unit test for `HasEval()` and `ReplaceEvalWithMap()`.
> feat: add eval regex and test

- casbin/enforcer.cpp
- tests/enforcer_synced_test.cpp
+ I think the reason these test can't work may be the deadlock of policyMutex (lock it twice) in load policy.
+ Use base enforcer's ClearPolicy and BuildRoleLink.
> fix: fix sync test by use base enforcer's ClearPolicy and BuildRoleLink.

- casbin/enforcer.cpp
- casbin/model/evaluator.cpp
- include/casbin/enforcer.h
- include/casbin/model/evaluator.h
- include/casbin/model/exprtk_config.h
- tests/benchmarks/model_b.cpp
- tests/model_enforcer_test.cpp
+ [feat: exprtk evaluator support RBAC with domain](https://github.com/casbin/casbin-cpp/commit/f7f7e3b83e79627a4653a481deea28eb89cbc389)
+ [feat: exprtk evaluator support rbac with pattern](https://github.com/casbin/casbin-cpp/commit/f0053dc88b83d6d726be683ab0214bc84041c968)
+ [feat: add benchmark for exprtk evaluator](https://github.com/casbin/casbin-cpp/commit/711c3b20a894661199c553ee3e19be0d0ac96e4a)
+ [perf: only compile once in Eval when eval string don't change.](https://github.com/casbin/casbin-cpp/commit/82bfac461b4e9c11454923a35e931c5092507cc9)
+ [fix: repair regex function and add function judge whether's null](https://github.com/casbin/casbin-cpp/commit/1bac8f190d7057a664f542ab1cfe472a5e24c9ab)
+ [fix: clean all symbol table to avoid haning pointer in …
> feat: Add benchmarks for exprtk evaluator.

- casbin/enforcer.cpp
- casbin/persist/adapter.h
- casbin/persist/file_adapter/file_adapter.cpp
- casbin/persist/file_adapter/file_adapter.h
- casbin/persist/string_adapter.cpp
- casbin/persist/string_adapter.h
- include/casbin/persist/adapter.h
- include/casbin/persist/file_adapter/file_adapter.h
- include/casbin/persist/string_adapter.h
fix: #200
I added `void LoadPolicy(std::string policy)` for Enforcer to pass policy to Adapter as a sting buffer, which could be called as the following code:
```
casbin::Enforcer e("./path/to/model.conf");
std::string policy = "p, alice, data1, read\np, bob, data2, write";
e.LoadPolicy(policy);
```
Since c++ doesn't support overloaded functions with the same number and type of parameters, I didn't add a constructor like `Enforcer(const std::string& model_path, const std::string &policy)` in issue #200, that conflicts with `Enforcer(const std::string& model_path, const std::string& policy_file)`
> fix: add StringAdapter for Enforcer to pass policy as string

- casbin/rbac/default_role_manager.cpp
- include/casbin/rbac/default_role_manager.h
* Share_ptr will cause performance loss.
* Share_ptr may cause circular reference of Roles, which will cause memeory leak.
* RoleManager take ownership of the resource, responsible for the application and release of Role*, Role only use this pointer.
Signed-off-by: Stonexx <1479765922@qq.com>
> perf: Remove shared_ptr in defaultRoleManager

- casbin/util/built_in_functions.cpp
- include/casbin/util/built_in_functions.h
part of: https://github.com/casbin/casbin-cpp/issues/209
> fix:add KeyMatch4() for built-in functions

- .github/workflows/python_binding.yml
- cmake/modules/Findjson.cmake
- setup.py
Fix: https://github.com/casbin/casbin-cpp/issues/220
This PR replaces the JSON lib with the original repository, followed
> https://json.nlohmann.me/integration/cmake/#fetchcontent
Meanwhile, delete Python 3.6 version for the error:
> Error: Version 3.6 with arch x64 not found
> fix: fix CI python issue

- casbin/effect/default_effector.cpp
- casbin/enforcer.cpp
- include/casbin/effect/default_effector.h
- include/casbin/effect/effector.h
- include/casbin/enforcer.h
- include/casbin/enforcer_interface.h
Rewrite the two functions m_enforce and MerggeEffects to synchronize them with Casbin (Golang)
```golang
func (e *Enforcer) enforce(matcher string, explains *[]string, rvals ...interface{}) (ok bool, err error)
func (e *DefaultEffector) MergeEffects(expr string, effects []Effect, matches []float64, policyIndex int, policyLength int) (Effect, int, error)
```
```cpp
// before
bool Enforcer::m_enforce(const std::string& matcher, std::shared_ptr<IEvaluator> evalator)
bool DefaultEffector ::MergeEffects(std::string expr, std::vector<Effect> effects, std::vector<float> results) 
// now
bool Enforcer::m_enforce(const std::string& matcher, std::vector<std::string>& explains, std::shared_ptr<IEvaluator> evalator)
Effect DefaultEffector::MergeEffects(const std::string& expr, const …
```
> feat: refactor the code, rewrite the two functions m_enforce and MergeEffects

- casbin/CMakeLists.txt
#205 
In "./casbin/CMakeLists.txt", line 79~82,
```cmake
set_target_properties(casbin PROPERTIES 
PREFIX ""
VERSION ${CMAKE_PROJECT_VERSION}
)
```
well, if i integrate `casbin-cpp` to my project as a thirdparty via cmake, the `VERSION` property will refer to my top project's `VERSION` property, cause `CMAKE_PROJECT_VERSION` means that, so it's unreasonable.
Instead, by
```cmake
set_target_properties(casbin PROPERTIES 
PREFIX ""
VERSION ${PROJECT_VERSION}
)
```
the `VERSION` property will refer to `casbin-cpp`'s top project's `VERSION` property, i think that's what we want.
> fix: set_target_properties's VERSION

- include/casbin/model/exprtk_config.h
Fix: https://github.com/casbin/casbin-cpp/issues/243
When the enforce function is called 10,000 times, the memory stays at 3MB for a while before it linearly increases to around 40MB. Using the performance analysis tool built into VS2022, snapshots were taken during the program’s runtime to compare the differences in memory and call counts. Clicking on the snapshot allows you to see which functions were called in the stack and what objects exist. 
After repeated comparisons, it was found that after the number of calls to GetExprtkFunction increased, many smart pointer objects were created and not released in time, causing the memory to continue to rise. I modified the function’s running logic, using an object pool to store the required objects and returning objects as needed. After …
> feat: fix memory leak in Enforce()

- casbin/enforcer_synced.cpp
- include/casbin/enforcer_synced.h
- tests/enforcer_synced_test.cpp
Fix: https://github.com/casbin/casbin-cpp/issues/244
Update the enforcer_synced class in the casbin-cpp library to match the go version of the Casbin.
The main content is to compare the enforcer_synced class in Go language with the cpp version, 
and add functions that are in the enforcer class of casbin-cpp but have not yet been added to the enforcer_synced class.
> feat: improve the synced enforcer like Go casbin

- casbin/util/built_in_functions.cpp
Instantiation of `std::regex` involves parsing and compiling the regular expression and should therefore be considered "expensive".
In this PR I changed some constant `std::regex` in the built-in-functions to static variables and moved those that are used multiple times to an anonymous namespace. I also introduced a few functions to reduce code duplication.
In the specific use case, this was tested with 1000 different requests. These were structured in such a way that the entire policy had to be run through each time.
The time saving was around 40%.
`casbintest` runs about 25% faster.
I tried to reflect functionality of the regex-expressions in the variable-names.
Unmodified version:
```
$ time ./casbintest >/dev/null
real    0m2.333s
user    0m1.968s
sys     0m0.230s
```
With this …
> feat: Improve performance of built-in-functions via static regexes

- casbin/util/built_in_functions.cpp
Follow-up on #249.
Testing showed significant better performance when *not* using `std::regex` for simple pattern-replacements.
Benchmarks built with CMAKE_BUILD_TYPE=Release in an ubuntu24.04 environment.
Performance of a bunch of benchmarks is improved
* almost 50% for e.g. `BenchmarkRBACModelSmall`
* about 20-30% for many other tests
```
~/casbin-cpp/build/tests/benchmarks (master) $ make -C ../.. > /dev/null && sleep 60 && ./casbin_benchmark
2024-12-10T11:21:36+00:00
Running ./casbin_benchmark
Run on (16 X 400 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x8)
L1 Instruction 32 KiB (x8)
L2 Unified 1024 KiB (x8)
L3 Unified 16384 KiB (x1)
Load Average: 0.30, 0.54, 0.75
------------------------------------------------------------------------------------
Benchmark …
```
> feat: Do not use regex for simple pattern-replacements to improve performance
